---
title: "DS HW4"
author: "Nataniel Tsai"
date: "7/21/2020"
output:
  word_document: default
  html_document: default
---



remotes::install_github("allisonhorst/palmerpenguins")
library(palmerpenguins) 
penguins

class(penguins$sex)
class(penguins$body_mass_g)
class(penguins$species)
class(penguins$island)
class(penguins$bill_length_mm)
class(penguins$bill_depth_mm)
class(penguins$flipper_length_mm)


levels(penguins$sex)
levels(penguins$body_mass_g)
levels(penguins$species)
levels(penguins$island)
levels(penguins$bill_length_mm)
levels(penguins$bill_depth_mm)
levels(penguins$flipper_length_mm)


summary(penguins$sex)
summary(penguins$island)
summary(penguins$species)
summary (penguins)

# Bar graph counts > colorblind palettes 
penguins %>%
  count(species) %>%
  ggplot() + geom_col(aes(x = species, y=n, fill = species))+ 
  geom_label(aes(x=species, y=n, label=n)) +
  scale_fill_manual(values = c("#009E73","#CC79A7","gray"))+
  theme_minimal()+
  labs(title = 'Number of Penguin Species')